name: harbour_of_fortune_rule_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.6.2
  
  # UI/Animations
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Utils
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

# Add this section to force older plugin versions
dependency_overrides:
  path_provider_android: 2.2.12
  video_player_android: 2.7.16

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default:21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/